### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by EndlessFractal** [Autmor/yourTurn#29]
Hi Autmor,

I hope this message finds you well. I wanted to reach out regarding this project. I noticed that there hasn't been any recent activity, and I wanted to check if you are still maintaining it.

If the project is currently inactive, I would be interested on maintaining it on my own. If you agree, I would appreciate it if you could update your module.json to point to my repository. This way, the community can benefit from the latest fixes and improvements.

Please let me know your thoughts on this. Thank you for your time!

Best regards,
EndlessFractal

**Comment by Autmor** [comment]
Hi, sorry for the late response.

Regarding changing the repo pointer, I will try to get that update out this weekend. Thanks!

**Comment by Autmor** [comment]
I am going to email foundry, and link them this chat, so the Foundry Module team knows that the developer is changing.

**Comment by Norc** [comment]
Hey @EndlessFractal,

Norc from Foundry customer support here. I just got an email request from @Autmor to transfer ownership of the [official Your Turn Foundry package listing](https://foundryvtt.com/packages/your-turn) to you, which will allow you to alter the listed module.json and release official updated versions yourself.

If this sounds good to you, please log into the Foundry website, use the Contact Us form, and include a link to this issue.

Thanks to you both for your work on this module!

**Comment by EndlessFractal** [comment]
Hello! As requested, I've sent the message through the contact form.

Thanks again for everything!

**Comment by EndlessFractal** [comment]
I confirm that the module ownership was successfully transferred.

Thank you!
