### ISSUE TITLE
DnD5e - Combat initiative issue

### ISSUE THREAD

**Issue by NotoriusNeo** [Autmor/yourTurn#4]
Hello!

Loving this mod so far, however there's a slight issue with the initiative.

What happens: When no encounter is created and the players roll for initiative: the banner shows up for some random player. When I press the button to begin the combat, the banner shows correctly again for the first in queue.

What should happen: When no encounter is created and the players roll for initiative: banner does not show. When I press the button to start the combat, the banner should show the first in queue.

Running:
![image](https://user-images.githubusercontent.com/89462237/175529421-627383ea-aafd-49dd-a3d5-1bd23de558c1.png)

None of the active modules should be interfering with the banner and/or initiative.

Demo:
![Animation](https://user-images.githubusercontent.com/89462237/175531349-c79079c8-d3a5-4688-96fc-864132984eef.gif)

**Comment by Armandeus66** [comment]
The same thing happens in Pathfinder 2E.

This module is awesome otherwise. Thanks for making it!

**Comment by Autmor** [comment]
I have seen the issue and I'll have a fix out within the next few weeks!

**Comment by jimmyiowa** [comment]
Alternatively, as an option if you wanted to toggle it on, first provide a module setting. But allow a user to enable an option to display "Roll Initiative" or something to that effect instead of the but that is currently there when initially creating an encounter.

**Comment by NotoriusNeo** [comment]
Fixed on the lastest release!
